### ISSUE TITLE
Automatically set role colors when created

### ISSUE THREAD

**Issue by joeldesante** [joeldesante/Harvey#22]
When a new course role is created an appropriate and unique color should be assigned to it.

Extracted from #3

**Comment by willuhmjs** [comment]
PR #3 is closed as completed, so this issue should be closed.

**Comment by joeldesante** [comment]
> PR #3 is closed as completed, so this issue should be closed.

This functionality was not implemented in #3 
As of now, all new roles created default to gray.

Instead, they should be automatically set to the correct color in the rainbow which is defined by their numerical value.

CS150 is a low number and is red
CS450 is a high number and is thus violet

**Comment by willuhmjs** [comment]
Great! I can do it.
