### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by LeoDog896** [joeldesante/Harvey#43]

**Comment by joeldesante** [comment]
Note that the original decision to not use TypeScript was to make the barrier for entry for members of the Discord Community lower.

With that in mind, I wouldn't be opposed to converting to TypeScript under the condition that the existing stack remains unchanged and the tool chain required for development remains simple.

See the following resource for info about TypeScript support w/ Sequelize.

https://sequelize.org/docs/v6/other-topics/typescript/
