### ISSUE TITLE
Welcome message is being sent twice when a user joins

### ISSUE THREAD

**Issue by joeldesante** [joeldesante/Harvey#46]
The welcome message is being sent twice for some reason when a new user joins

**Comment by willuhmjs** [comment]
Does this happen every time a new user joins?

**Comment by joeldesante** [comment]
> Does this happen every time a new user joins?

Yes, it seems so. I thought it might have been an issue where multiple instances of the bot were running on the server but even after resetting the deployment, the issue seems to persist. For now I've just been manually deleting the duplicate messages.

**Comment by joeldesante** [comment]
It appears that this issue is no longer occurring. This leads me to believe that this was caused by some error in the container orchestration rather than in the code itself.

Only one instance of Harvey should be running at a given time. Harvey is not designed to have two instances running at once.
