### ISSUE TITLE
Rename parent-channel to parent-category

### ISSUE THREAD

**Issue by willuhmjs** [joeldesante/Harvey#48]
In `setCourseRoleChannel.js`, the category channel option is named `parent-channel` instead of `parent-category`, which is ambigious. The description of the command accurately describes it, so the name should as well.

```js
.addChannelOption(new SlashCommandChannelOption()
      .setName("parent-channel") // Change this to "parent-category"
      .setDescription("The category in which the course chats will reside.")
      .setRequired(true)
)
```

**Comment by joeldesante** [comment]
Good idea. The original name is due to the fact that categories are seen as channels by discord. But from a UX perspective this makes more sense.

**Comment by willuhmjs** [comment]
I also recommend using the `addChannelType` method to the channel option of the slash command builder. This limits the `parent-category` channel to the category type.
