### ISSUE TITLE
Set `dev` as primary branch for project

### ISSUE THREAD

**Issue by malakhite** [joeldesante/Harvey#64]
The primary branch for the repository should be changed to `dev` in the repository settings in order to simplify contributions for new contributors. I didn't find out about this until after I'd already created my [first PR](https://github.com/joeldesante/Harvey/pull/62), and it definitely complicated things, given the scope of changes I was proposing.

**Comment by joeldesante** [comment]
Good idea! I will look into what this entails.

**Comment by joeldesante** [comment]
Primary branch updated
